<?php

// Test case file which will fail to tokenize as the nested level > 50 deep.

if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 5
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 10
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 15
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 20
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 25
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 30
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 35
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 40
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 45
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 50
if ($a) { if ($a) { if ($a) { if ($a) { if ($a) { // 55
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
}}}}}
