name: Test

on:
  # Run on pushes to `master` and on all pull requests.
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.ref != 'refs/heads/develop' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['5.4', '7.0', '7.4', '8.0', '8.1', '8.2']

    name: "Lint: PHP ${{ matrix.php }}"

    continue-on-error: ${{ matrix.php == '8.2' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: 'development'
          coverage: none
          tools: cs2pr

      - name: Install Composer dependencies - normal
        if: ${{ matrix.php < 8.2 }}
        uses: "ramsey/composer-install@v2"

      # For the PHP "nightly", we need to install with ignore platform reqs as not all dependencies allow it yet.
      - name: Install Composer dependencies - with ignore platform
        if: ${{ matrix.php >= 8.2 }}
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --ignore-platform-reqs

      - name: Lint against parse errors
        run: composer lint -- --checkstyle | cs2pr


  #### TEST STAGE ####
  test:
    if: ${{ github.ref != 'refs/heads/develop' }}
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      # Keys:
      # - risky: Whether to run with tests which check for being in sync with PHPCS.
      # - experimental: Whether the build is "allowed to fail".
      matrix:
        # The GHA matrix works different from Travis.
        # You can define jobs here and then augment them with extra variables in `include`,
        # as well as add extra jobs in `include`.
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
        #
        # IMPORTANT: test runs shouldn't fail because of PHPCS being incompatible with a PHP version.
        # - PHPCS will run without errors on PHP 5.4 - 7.2 on any version.
        # - PHP 7.3 needs PHPCS 2.9.2 and 3.3.1+ to run without errors.
        #   On PHPCS 2.x our tests won't fail though, but on PHPCS 3.x < 3.3.1 they will.
        # - PHP 7.4 needs PHPCS 3.5.0+ to run without errors.
        #   On PHPCS 2.x our tests won't fail though, but on PHPCS 3.x < 3.5.0 they will.
        # - PHP 8.0 needs PHPCS 3.5.7+ to run without errors.
        # - PHP 8.1 needs PHPCS 3.6.1+ to run without errors.
        #
        # The matrix is set up so as not to duplicate the builds which are run for code coverage.
        php: ['5.5', '5.6', '7.0', '7.1', '7.2']
        phpcs_version: ['2.6.0', '2.9.2', '3.1.0', 'dev-master']
        risky: [false]
        experimental: [false]

        include:
          # Complement the builds run in code coverage to complete the matrix and prevent issues
          # with PHPCS versions incompatible with certain PHP versions.
          - php: '8.1'
            phpcs_version: '3.6.1'
            risky: false
            experimental: false

          - php: '8.0'
            phpcs_version: 'dev-master'
            risky: false
            experimental: false
            extensions: ':iconv' # Run one build with iconv disabled.
          - php: '8.0'
            phpcs_version: '3.5.7'
            risky: false
            experimental: false

          - php: '7.4'
            phpcs_version: 'dev-master'
            risky: false
            experimental: false
          - php: '7.4'
            phpcs_version: '3.5.0'
            risky: false
            experimental: false

          - php: '7.3'
            phpcs_version: 'dev-master'
            risky: false
            experimental: false
          - php: '7.3'
            phpcs_version: '3.3.1'
            risky: false
            experimental: false
          - php: '7.3'
            phpcs_version: '2.6.0'
            risky: false
            experimental: false

          - php: '5.4'
            phpcs_version: '3.1.0'
            risky: false
            experimental: false
          - php: '5.4'
            phpcs_version: '2.9.2'
            risky: false
            experimental: false

          # One extra build to verify issues around PHPCS annotations when they weren't fully accounted for yet.
          - php: '7.2'
            phpcs_version: '3.2.0'
            risky: false
            experimental: false

          # And a few more to verify various tokenizer issues in older PHPCS versions.
          - php: '5.6'
            phpcs_version: '2.8.1'
            risky: false
            experimental: false
          - php: '7.0'
            phpcs_version: '2.7.1'
            risky: false
            experimental: false

          # Experimental builds. These are allowed to fail.
          - php: '8.2'
            phpcs_version: 'dev-master'
            risky: false
            experimental: true

          - php: '7.4'
            phpcs_version: '4.0.x-dev'
            risky: false
            experimental: true

          # Run risky tests separately.
          - php: '7.4'
            phpcs_version: '4.0.x-dev'
            risky: true
            experimental: true

          - php: '7.4'
            phpcs_version: 'dev-master'
            risky: true
            experimental: true

    name: "Test: PHP ${{ matrix.php }} - PHPCS ${{ matrix.phpcs_version }}${{ matrix.risky == true && ' (risky)' || '' }}"

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # On stable PHPCS versions, allow for PHP deprecation notices.
      # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
      - name: Setup ini config
        id: set_ini
        run: |
          if [[ "${{ matrix.phpcs_version }}" != "dev-master" && "${{ matrix.phpcs_version }}" != "4.0.x-dev" ]]; then
            echo '::set-output name=PHP_INI::error_reporting=E_ALL & ~E_DEPRECATED, display_errors=On'
          else
            echo '::set-output name=PHP_INI::error_reporting=-1, display_errors=On'
          fi

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: none

      - name: 'Composer: set PHPCS version for tests'
        run: composer require --no-update squizlabs/php_codesniffer:"${{ matrix.phpcs_version }}"

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies - normal
        if: ${{ matrix.php < 8.2 }}
        uses: "ramsey/composer-install@v2"

      # For the PHP "nightly", we need to install with ignore platform reqs as not all dependencies allow it yet.
      - name: Install Composer dependencies - with ignore platform
        if: ${{ matrix.php >= 8.2 }}
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --ignore-platform-reqs

      - name: Run the unit tests (non-risky)
        if: matrix.risky == false
        run: vendor/bin/phpunit --no-coverage
        env:
          PHPCS_VERSION: ${{ matrix.phpcs_version == '4.0.x-dev' && '4.0.0' || matrix.phpcs_version }}

      - name: Run the unit tests (risky)
        if: ${{ matrix.risky }}
        # "nothing" is excluded to force PHPUnit to ignore the <exclude> settings in phpunit.xml.dist.
        run: vendor/bin/phpunit --no-coverage --group compareWithPHPCS --exclude-group nothing
        env:
          PHPCS_VERSION: ${{ matrix.phpcs_version == '4.0.x-dev' && '4.0.0' || matrix.phpcs_version }}


  #### CODE COVERAGE STAGE ####
  # N.B.: Coverage is only checked on the lowest and highest stable PHP versions
  # and a low/high of each major for PHPCS.
  # These builds are left out off the "test" stage so as not to duplicate test runs.
  coverage:
    # No use running the coverage builds if there are failing test builds.
    needs: test
    # The default condition is success(), but this is false when one of the previous jobs is skipped
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: '8.1'
            phpcs_version: 'dev-master'
          - php: '7.3'
            phpcs_version: '2.9.2'
            extensions: ':iconv' # Run one build with iconv disabled.
          - php: '5.4'
            phpcs_version: 'dev-master'
          - php: '5.4'
            phpcs_version: '2.6.0'

    name: "Coverage: PHP ${{ matrix.php }} - PHPCS ${{ matrix.phpcs_version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # On stable PHPCS versions, allow for PHP deprecation notices.
      # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
      - name: Setup ini config
        id: set_ini
        run: |
          if [ "${{ matrix.phpcs_version }}" != "dev-master" ]; then
            echo '::set-output name=PHP_INI::error_reporting=E_ALL & ~E_DEPRECATED, display_errors=On'
          else
            echo '::set-output name=PHP_INI::error_reporting=-1, display_errors=On'
          fi

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: xdebug

      - name: 'Composer: adjust dependencies'
        run: |
          # Set a specific PHPCS version.
          composer require --no-update squizlabs/php_codesniffer:"${{ matrix.phpcs_version }}" --no-scripts

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Grab PHPUnit version
        id: phpunit_version
        run: >
          echo ::set-output name=VERSION::
          $(vendor/bin/phpunit --version | grep --only-matching --max-count=1 --extended-regexp '\b[0-9]+\.[0-9]+')

      - name: "DEBUG: Show grabbed version"
        run: echo ${{ steps.phpunit_version.outputs.VERSION }}

      # PHPUnit 9.3 started using PHP-Parser for code coverage causing some of our coverage builds to fail.
      # As of PHPUnit 9.3.4, a cache warming option is available.
      # Using that option prevents issues with PHP-Parser backfilling PHP tokens when PHPCS does not (yet),
      # which would otherwise cause tests to fail on tokens being available when they shouldn't be.
      - name: "Warm the PHPUnit cache (PHPUnit 9.3+)"
        if: ${{ steps.phpunit_version.outputs.VERSION >= '9.3' }}
        run: vendor/bin/phpunit --coverage-cache ./build/phpunit-cache --warm-coverage-cache

      - name: "Run the unit tests with code coverage (PHPUnit < 9.3)"
        if: ${{ steps.phpunit_version.outputs.VERSION < '9.3' }}
        run: vendor/bin/phpunit
        env:
          PHPCS_VERSION: ${{ matrix.phpcs_version }}

      - name: "Run the unit tests with code coverage (PHPUnit 9.3+)"
        if: ${{ steps.phpunit_version.outputs.VERSION >= '9.3' }}
        run: vendor/bin/phpunit --coverage-cache ./build/phpunit-cache
        env:
          PHPCS_VERSION: ${{ matrix.phpcs_version }}

      # Uploading the results with PHP Coveralls v1 won't work from GH Actions, so switch the PHP version.
      - name: Switch to PHP 7.4
        if: ${{ success() && matrix.php != '7.4' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install Coveralls
        if: ${{ success() }}
        run: composer require php-coveralls/php-coveralls:"^2.4.2"

      - name: Upload coverage results to Coveralls
        if: ${{ success() }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php }}-phpcs-${{ matrix.phpcs_version }}
        run: vendor/bin/php-coveralls -v -x build/logs/clover.xml

  coveralls-finish:
    needs: coverage
    if: always() && needs.coverage.result == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
